In [9]:
import numpy as np
import ipywidgets as widgets
'''
size_slider = widgets.IntSlider(value=2, min=1, max=10, step=1, description='size')
generate_button = widgets.Button(description='generate')
display(size_slider,generate_button)

def generate_matrix(change=None):
    global A,b, wiersze, kolumny
    if change is not None:
        size =size_slider.value
        A = np.random.randint(low=0, high=100, size=(size, size)).astype(float)  # Losowe wartości z zakresu [0, 10)
        b = np.random.randint(low=0, high=100, size=size).astype(float)   # Losowy wektor o długości size z zakresu [0, 10)
        print("Macierz A:", '\n', A, '\n \n', "Wektor b:", '\n', b)
        wiersze = A.shape[0]
        kolumny = A.shape[1]


generate_button.on_click(generate_matrix)
generate_matrix()'''

A = np.array([[7, 28], [28, 141]], dtype=float)  # Convert to float
b = np.array([24, 119.5])


#A = np.array([[4, 2, 2], [2, 5, 3], [2, 3, 6]])
#b = np.array([7, 4, 9])
wiersze = A.shape[0]
kolumny = A.shape[1]

## Metoda Eliminacji Gaussa
Metoda eliminacji Gaussa, znana również jako metoda eliminacji współczynników lub metoda schodkowa, jest fundamentalnym narzędziem wykorzystywanym w matematyce. Jest najczęściej stosowaną skończoną metodą numerycznego rozwiązywania nieosobliwych układów równań liniowych. Jest to metoda bezpośrednia, czyli pozwalająca na uzyskanie wyniku po określonej liczbie operacji. Jej głównym celem jest przekształcenie macierzy współczynników układu równań liniowych w taki sposób, aby można było efektywnie rozwiązać go, eliminując niewiadome krok po kroku. Złożoność tej metody wynosi $\mathcal{O}(n^3)$, co sprawia, że jest ona stosunkowo wydajna dla większych układów równań. Poniżej przedstawiono algorytm metody eliminacji Gaussa.

### Algorytm obliczania:
**Krok 1:**
Początkowy układ równań:
$$
A^{(1)}x = b^{(1)}:
\begin{bmatrix}
a_{11}^{(1)} & a_{12}^{(1)} & \ldots & a_{1n}^{(1)} \\
a_{21}^{(1)} & a_{22}^{(1)} & \ldots & a_{2n}^{(1)} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1}^{(1)} & a_{n2}^{(1)} & \ldots & a_{nn}^{(1)}
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix}
=
\begin{bmatrix}
b_1^{(1)} \\
b_2^{(1)} \\
\vdots \\
b_n^{(1)}
\end{bmatrix}
$$

**Krok 2:**
Następnie odejmowanie od i-tego wiersza wiersza pierwszego, przemnożonego przez $\alpha = \frac{a_{i1}^{(1)}}{a_{11}^{(1)}}$. Otrzymujemy $A^{(2)}x = b^{(2)}$:
$$
\begin{bmatrix}
a_{11}^{(1)} & a_{12}^{(1)} & \ldots & a_{1n}^{(1)} \\
0 & a_{22}^{(2)} & \ldots & a_{2n}^{(2)} \\
\vdots & \vdots & \ddots & \vdots \\
0 & a_{n2}^{(2)} & \ldots & a_{nn}^{(2)}
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix}
=
\begin{bmatrix}
b_1^{(1)} \\
b_2^{(2)} \\
\vdots \\
b_n^{(2)}
\end{bmatrix}
$$

**Krok 3:**
Postępowanie w ten sposób z kolejnymi wierszami, aż ostatecznie uzyska się $A^{(n)}x = b^{(n)}$:
$$
\begin{bmatrix}
a_{11}^{(1)} & a_{12}^{(1)} & \ldots & a_{1n}^{(1)} \\
0 & a_{22}^{(2)} & \ldots & a_{2n}^{(2)} \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \ldots & a_{nn}^{(n)}
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix}
=
\begin{bmatrix}
b_1^{(1)} \\
b_2^{(2)} \\
\vdots \\
b_n^{(n)}
\end{bmatrix}
$$

**Krok 4:**
Rozwiązywanie układu poprzez małą liczbę działań arytmetycznych, korzystając z zależności rekurencyjnej:
$$
x_n = \frac{b^{(n)}_n}{a^{(n)}_{nn}}
$$
$$
x_i = \frac{b^{(i)}_i - a^{i}_{in}x_n - \ldots - a^{i}_{ii}x_{i+1}}{a^{(i)}_{ii}}
$$
gdzie $i = n - 1, n - 2, \ldots, 1$



In [10]:
def gauss_elimination(A, b):

    """
    Metoda eliminacji Gaussa dla rozwiązywania układów równań liniowych.
    """

    Ap = A.copy()
    bp = b.copy()
    for i in range (wiersze -1): #iteracja po kolumnach, bez ostatniej
        for j in range(i + 1, wiersze): #iteracja po wierszach, bez pierwszego
            wsp = Ap[j, i] / Ap[i, i]  #współczynnik eliminacji
            Ap[j, :] -= Ap[i, :] * wsp #odjęcie od j-tego wiersza wartości z kolejnego wiersza pomnożonego przez współczynnik
            bp[j] -= bp[i] * wsp

    x = np.zeros(wiersze) # wektor rozwiązań
    for i in range(wiersze - 1, -1, -1): #iteracja od ostatniego do pierwszego
        x[i] = (bp[i] - np.dot(Ap[i, :], x)) / Ap[i, i] #obliczanie wartości zmiennej

    print ("Macierz A:",'\n',Ap,'\n \n', "Wektor b:",'\n',b,'\n \n',"Wektor rozwiązań:",'\n',x)
    
gauss_elimination(A,b) 

Macierz A: 
 [[ 7. 28.]
 [ 0. 29.]] 
 
 Wektor b: 
 [ 24.  119.5] 
 
 Wektor rozwiązań: 
 [0.18719212 0.81034483]


## Faktoryzacja LU

Faktoryzacja LU (ang. **L**ower-**U**pper) jest techniką rozkładu macierzy kwadratowej $A$ na iloczyn dwóch macierzy $L$ i $U$, gdzie $L$ jest macierzą dolnotrójkątną z jedynkami na przekątnej, a $U$ jest macierzą górnotrójkątną.

Faktoryzacja LU jest szeroko stosowana do rozwiązywania układów równań oraz obliczeń odwrotnych.


In [6]:
def LU_Factorization(A):
    """
    Faktoryzacja LU macierzy A.
    """

    #inicjacja macierzy L i U o rozmiarze macierzy A
    L = np.eye(wiersze) #L=I (macierz jednostkowa)
    U = A.copy() #U = A
    np.fill_diagonal(U, A.diagonal()) #wypełenie przekątnej macierzy U wartościami z przekątnej macierzy A
    
    if wiersze == kolumny: #czy macierz A jest kwadratowa
        #algorytm z wykładu
        for i in range (wiersze-1):
            if not np.isclose(U[i, i], 0.0): #uniknięcie dzielenia przez 0
                for j in range (i+1,wiersze):
                    if i == 0:
                        print ('L:\n' ,L)
                        print ('U:\n',U)
                    L[j,i] = U[j,i]/U[i,i]
                    U[j, i:wiersze] = U[j, i:wiersze] - L[j, i] * U[i, i:wiersze]
                    print ('L:\n' ,L)
                    print ('U:\n',U)
    else:
        print("Macierz nie jest kwadratowa")


    #print ("\nMacierz L:\n",L, '\n ,Macierz U:\n',U)
    #print("Macierz U:\n",U)

LU_Factorization(A)

L:
 [[1. 0.]
 [0. 1.]]
U:
 [[  7.  28.]
 [ 28. 141.]]
L:
 [[1. 0.]
 [4. 1.]]
U:
 [[ 7. 28.]
 [ 0. 29.]]


## Faktoryzacja Cholesky'ego

Faktoryzacja Cholesky'ego jest techniką rozkładu macierzy symetrycznej i dodatnio określonej $A$ na iloczyn dwóch macierzy: $L$ (macierz dolnotrójkątna) oraz jej transpozycji $L^T$.

Faktoryzacja Cholesky'ego  ogranicza liczbę koniecznych operacji w porównaniu do ogólnych metod rozkładu LU.


In [7]:

def Cholesky_Factorization():
    """
    Dokładna metoda faktoryzacji Cholesky'ego.
    """
    #M = np.array([[4,2,2], [2,5,3], [2,3,6]])
    
    #rozmiar macierzy
    m = A.shape[0]

    #inicjalizacja macierzy trojkatnej dolnej o rozmiarze macierzy M
    Ml = np.zeros((m, m))

    print (Ml, '\n')

    #sprawdzenie czy macierz jest kwadratowa
    if A.shape[0] == A.shape[1]:
        for k in range(m):
            for j in range(k, m):
                #w przypadku przekątnej
                if k == j:
                    Ml[k, k] = np.sqrt((A[k, k])  - np.sum(Ml[k, :k] ** 2))

                #dolna czesc macierzy
                else:
                    Ml[j,k] = (A[j,k] - np.sum(Ml[j, :k] * Ml[k, :k])) / Ml[k,k]
                print(Ml, "\n")
          # Transpozycja końcowej macierzy M1
    M1_transposed = Ml.T

    print("Macierz transponowana (M1_transposed):\n")
    print(M1_transposed, "\n")
        
    return Ml
L = Cholesky_Factorization()

[[0. 0.]
 [0. 0.]] 

[[2.64575131 0.        ]
 [0.         0.        ]] 

[[ 2.64575131  0.        ]
 [10.58300524  0.        ]] 

[[ 2.64575131  0.        ]
 [10.58300524  5.38516481]] 

Macierz transponowana (M1_transposed):

[[ 2.64575131 10.58300524]
 [ 0.          5.38516481]] 

